/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ogy7SI6fHkZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"

export function AiGeneratedPost() {
  return (
    (<section className="w-full py-12 md:py-16 lg:py-20">
      <div className="container px-4 md:px-6">
        <div className="mx-auto max-w-xl space-y-6">
          <div className="grid gap-2">
            <label htmlFor="title" className="text-sm font-medium">
              Blog Post Title
            </label>
            <Input
              id="title"
              type="text"
              placeholder="Enter your blog post title"
              className="w-full" />
          </div>
          <div className="grid gap-2">
            <Button
              onClick={(e) => {
                e.preventDefault()
                const generatedDescription =
                  "This is a sample AI-generated blog post description. It provides a concise overview of the key points and themes covered in the blog post."
                setDescription(generatedDescription)
              }}>
              Generate Description
            </Button>
            <Textarea
              id="description"
              rows={4}
              placeholder="Your AI-generated description will appear here"
              className="w-full" />
            <div className="flex items-center justify-end gap-2">
              <Button
                variant="ghost"
                size="icon"
                onClick={() => {
                  navigator.clipboard.writeText(description)
                }}>
                <CopyIcon className="h-4 w-4" />
                <span className="sr-only">Copy Description</span>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>)
  );
}

function CopyIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </svg>)
  );
}
