/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BUVHsiyLz38
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Link } from "react-router-dom";

export function feeds() {
  return (
    (<div className="container mx-auto px-4 py-12 md:px-6 lg:py-16">
      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        <div
          className="group relative overflow-hidden rounded-lg border bg-background transition-all duration-300 hover:shadow-lg">
          {/* <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Post</span>
          </Link> */}
          <img
            src="/placeholder.svg"
            alt="Blog Post Image"
            width={600}
            height={400}
            className="h-60 w-full object-cover transition-all duration-300 group-hover:scale-105" />
          <div className="p-4">
            <h3
              className="text-lg font-semibold text-foreground transition-colors duration-300 group-hover:text-primary">
              Mastering React Hooks: A Comprehensive Guide
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">Published on May 15, 2023</p>
          </div>
        </div>
        <div
          className="group relative overflow-hidden rounded-lg border bg-background transition-all duration-300 hover:shadow-lg">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Post</span>
          </Link>
          <img
            src="/placeholder.svg"
            alt="Blog Post Image"
            width={600}
            height={400}
            className="h-60 w-full object-cover transition-all duration-300 group-hover:scale-105" />
          <div className="p-4">
            <h3
              className="text-lg font-semibold text-foreground transition-colors duration-300 group-hover:text-primary">
              Unleashing the Power of Tailwind CSS: A Beginner's Guide
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">Published on April 20, 2023</p>
          </div>
        </div>
        <div
          className="group relative overflow-hidden rounded-lg border bg-background transition-all duration-300 hover:shadow-lg">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Post</span>
          </Link>
          <img
            src="/placeholder.svg"
            alt="Blog Post Image"
            width={600}
            height={400}
            className="h-60 w-full object-cover transition-all duration-300 group-hover:scale-105" />
          <div className="p-4">
            <h3
              className="text-lg font-semibold text-foreground transition-colors duration-300 group-hover:text-primary">
              Exploring the Serverless Revolution: A Practical Guide
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">Published on March 10, 2023</p>
          </div>
        </div>
        <div
          className="group relative overflow-hidden rounded-lg border bg-background transition-all duration-300 hover:shadow-lg">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Post</span>
          </Link>
          <img
            src="/placeholder.svg"
            alt="Blog Post Image"
            width={600}
            height={400}
            className="h-60 w-full object-cover transition-all duration-300 group-hover:scale-105" />
          <div className="p-4">
            <h3
              className="text-lg font-semibold text-foreground transition-colors duration-300 group-hover:text-primary">
              Optimizing React Performance: Techniques and Best Practices
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">Published on February 28, 2023</p>
          </div>
        </div>
        <div
          className="group relative overflow-hidden rounded-lg border bg-background transition-all duration-300 hover:shadow-lg">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Post</span>
          </Link>
          <img
            src="/placeholder.svg"
            alt="Blog Post Image"
            width={600}
            height={400}
            className="h-60 w-full object-cover transition-all duration-300 group-hover:scale-105" />
          <div className="p-4">
            <h3
              className="text-lg font-semibold text-foreground transition-colors duration-300 group-hover:text-primary">
              Building a Scalable Design System with Figma
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">Published on January 15, 2023</p>
          </div>
        </div>
        <div
          className="group relative overflow-hidden rounded-lg border bg-background transition-all duration-300 hover:shadow-lg">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Post</span>
          </Link>
          <img
            src="/placeholder.svg"
            alt="Blog Post Image"
            width={600}
            height={400}
            className="h-60 w-full object-cover transition-all duration-300 group-hover:scale-105" />
          <div className="p-4">
            <h3
              className="text-lg font-semibold text-foreground transition-colors duration-300 group-hover:text-primary">
              Mastering TypeScript: A Comprehensive Guide for JavaScript Developers
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">Published on December 1, 2022</p>
          </div>
        </div>
      </div>
    </div>)
  );
}
